export const UNIVERSITY_LIST_REQUEST = 'UNIVERSITY_LIST_REQUEST';
export const UNIVERSITY_LIST_SUCCESS = 'UNIVERSITY_LIST_SUCCESS';
export const UNIVERSITY_LIST_FAIL = 'UNIVERSITY_LIST_FAIL';

export const CREATE_UNIVERSITY_REQUEST = 'CREATE_UNIVERSITY_REQUEST';
export const CREATE_UNIVERSITY_SUCCESS = 'CREATE_UNIVERSITY_SUCCESS';
export const CREATE_UNIVERSITY_FAIL = 'CREATE_UNIVERSITY_FAIL';

export const RESET_UNIVERSITY = 'RESET_UNIVERSITY';
