export const UNIVERSITY_PROFILE_BASIC_REQUEST =
  'UNIVERSITY_PROFILE_BASIC_REQUEST';
export const UNIVERSITY_PROFILE_BASIC_SUCCESS =
  'UNIVERSITY_PROFILE_BASIC_SUCCESS';
export const UNIVERSITY_PROFILE_BASIC_FAIL = 'UNIVERSITY_PROFILE_BASIC_FAIL';

export const UNIVERSITY_PROFILE_BASIC_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_BASIC_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_BASIC_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_BASIC_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_BASIC_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_BASIC_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_MOU_REQUEST = 'UNIVERSITY_PROFILE_MOU_REQUEST';
export const UNIVERSITY_PROFILE_MOU_SUCCESS = 'UNIVERSITY_PROFILE_MOU_SUCCESS';
export const UNIVERSITY_PROFILE_MOU_FAIL = 'UNIVERSITY_PROFILE_MOU_FAIL';

export const UNIVERSITY_PROFILE_MOU_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_MOU_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_MOU_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_MOU_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_MOU_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_MOU_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_CONTACT_REQUEST =
  'UNIVERSITY_PROFILE_CONTACT_REQUEST';
export const UNIVERSITY_PROFILE_CONTACT_SUCCESS =
  'UNIVERSITY_PROFILE_CONTACT_SUCCESS';
export const UNIVERSITY_PROFILE_CONTACT_FAIL =
  'UNIVERSITY_PROFILE_CONTACT_FAIL';

export const UNIVERSITY_PROFILE_CONTACT_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_CONTACT_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_CONTACT_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_CONTACT_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_CONTACT_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_CONTACT_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_REQUEST =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_REQUEST';
export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_SUCCESS =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_SUCCESS';
export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_FAIL =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_FAIL';

export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_FININCIAL_AGREEMENT_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_UPDATES_REQUEST =
  'UNIVERSITY_PROFILE_UPDATES_REQUEST';
export const UNIVERSITY_PROFILE_UPDATES_SUCCESS =
  'UNIVERSITY_PROFILE_UPDATES_SUCCESS';
export const UNIVERSITY_PROFILE_UPDATES_FAIL =
  'UNIVERSITY_PROFILE_UPDATES_FAIL';

export const UNIVERSITY_PROFILE_UPDATES_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_UPDATES_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_UPDATES_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_UPDATES_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_UPDATES_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_UPDATES_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_DOCUMENT_REQUEST =
  'UNIVERSITY_PROFILE_DOCUMENT_REQUEST';
export const UNIVERSITY_PROFILE_DOCUMENT_SUCCESS =
  'UNIVERSITY_PROFILE_DOCUMENT_SUCCESS';
export const UNIVERSITY_PROFILE_DOCUMENT_FAIL =
  'UNIVERSITY_PROFILE_DOCUMENT_FAIL';

export const UNIVERSITY_PROFILE_DOCUMENT_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_DOCUMENT_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_DOCUMENT_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_DOCUMENT_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_DOCUMENT_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_DOCUMENT_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_APPLICATION_REQUEST =
  'UNIVERSITY_PROFILE_APPLICATION_REQUEST';
export const UNIVERSITY_PROFILE_APPLICATION_SUCCESS =
  'UNIVERSITY_PROFILE_APPLICATION_SUCCESS';
export const UNIVERSITY_PROFILE_APPLICATION_FAIL =
  'UNIVERSITY_PROFILE_APPLICATION_FAIL';

export const UNIVERSITY_PROFILE_APPLICATION_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_APPLICATION_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_APPLICATION_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_APPLICATION_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_APPLICATION_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_APPLICATION_UPDATE_FAIL';

export const UNIVERSITY_PROFILE_GUEST_REQUEST =
  'UNIVERSITY_PROFILE_GUEST_REQUEST';
export const UNIVERSITY_PROFILE_GUEST_SUCCESS =
  'UNIVERSITY_PROFILE_GUEST_SUCCESS';
export const UNIVERSITY_PROFILE_GUEST_FAIL = 'UNIVERSITY_PROFILE_GUEST_FAIL';

export const UNIVERSITY_PROFILE_MEETING_REQUEST =
  'UNIVERSITY_PROFILE_MEETING_REQUEST';
export const UNIVERSITY_PROFILE_MEETING_SUCCESS =
  'UNIVERSITY_PROFILE_MEETING_SUCCESS';
export const UNIVERSITY_PROFILE_MEETING_FAIL =
  'UNIVERSITY_PROFILE_MEETING_FAIL';

export const UNIVERSITY_PROFILE_PROGRAM_REQUEST =
  'UNIVERSITY_PROFILE_PROGRAM_REQUEST';
export const UNIVERSITY_PROFILE_PROGRAM_SUCCESS =
  'UNIVERSITY_PROFILE_PROGRAM_SUCCESS';
export const UNIVERSITY_PROFILE_PROGRAM_FAIL =
  'UNIVERSITY_PROFILE_PROGRAM_FAIL';

export const UNIVERSITY_PROFILE_PROGRAM_UPDATE_REQUEST =
  'UNIVERSITY_PROFILE_PROGRAM_UPDATE_REQUEST';
export const UNIVERSITY_PROFILE_PROGRAM_UPDATE_SUCCESS =
  'UNIVERSITY_PROFILE_PROGRAM_UPDATE_SUCCESS';
export const UNIVERSITY_PROFILE_PROGRAM_UPDATE_FAIL =
  'UNIVERSITY_PROFILE_PROGRAM_UPDATE_FAIL';
